apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: books-api-ingress
spec:
  rules:
    - host: books.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: books-api-service
                port:
                  number: 80
